# Generated by Django 5.1.6 on 2025-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_aulasconcluidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aulasconcluidas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
